# Generated by Django 3.1 on 2020-08-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='vission',
            new_name='vision',
        ),
    ]
