# Generated by Django 3.1 on 2020-08-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
    ]
