# Generated by Django 3.1 on 2020-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200810_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='no_of_beds',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
