# Generated by Django 3.1 on 2020-08-10 18:57

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='reserve',
            name='phone_no',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
