# Generated by Django 3.1 on 2020-08-10 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200811_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='reserve',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91123456789'. Up to 12 digits allowed.", regex='^\\+?91?\\d{9,15}$')]),
        ),
    ]
