# Generated by Django 3.1 on 2020-08-18 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200811_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='notes',
        ),
        migrations.AddField(
            model_name='reserve',
            name='check_in',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='check_out',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='no_of_adult',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserve',
            name='no_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
