# Generated by Django 3.1 on 2020-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200818_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='no_of_adult',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='no_of_children',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
