# Generated by Django 3.1 on 2020-08-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20200819_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='r_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
