# Generated by Django 3.1 on 2020-08-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200821_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='r_no',
            field=models.CharField(max_length=100),
        ),
    ]
