# Generated by Django 3.1 on 2020-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200821_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='room_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
