# Generated by Django 3.1 on 2020-08-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='staff/')),
            ],
        ),
    ]
