# Generated by Django 3.1 on 2020-08-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
